# Generated by Django 3.2.5 on 2022-11-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choristes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=24)),
                ('prenom', models.CharField(max_length=24)),
                ('voice', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Atendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('choriste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.choristes')),
            ],
        ),
    ]
