# Generated by Django 3.2.5 on 2022-11-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_attendance_is_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
    ]
