# Generated by Django 3.2.5 on 2022-12-23 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attendance_is_present'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choristes',
            new_name='Choriste',
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('moment_liturgique', models.CharField(max_length=50)),
                ('temps_liturgique', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('date_added', models.DateField(auto_now=True)),
                ('verified', models.BooleanField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.choriste')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=50)),
                ('is_present', models.BooleanField()),
                ('attendances', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.attendance')),
                ('choriste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.choriste')),
            ],
        ),
    ]
